In [1]:
protein_groups_file = "../../test_data/system_tests/quicktests/mq_evidence/proteinGroups.txt.shortened.txt"
protein_groups_file_double = f"{protein_groups_file}.double.txt"
evidence_file = "../../test_data/system_tests/quicktests/mq_evidence/shortened_input.tsv"
annotated_file = f"{evidence_file}.protgroup_annotated.tsv"
aq_reformatted_file = "../../test_data/system_tests/quicktests/mq_evidence/shortened_input.tsv.protgroup_annotated.tsv.maxquant_evidence.aq_reformat.tsv"

In [10]:
import directlfq.utils


directlfq.utils.add_mq_protein_group_ids_if_applicable_and_obtain_annotated_file(mq_file=evidence_file, mq_protein_group_file=protein_groups_file, input_type_to_use="maxquant_evidence", columns_to_add=[])

'../../test_data/system_tests/quicktests/mq_evidence/shortened_input.tsv.protgroup_annotated.tsv'

In [11]:
import pandas as pd
protein_groups_df = pd.read_csv(protein_groups_file, sep="\t")
evidence_df = pd.read_csv(evidence_file, sep="\t")
annotated_df = pd.read_csv(annotated_file, sep="\t")

In [13]:
import directlfq.utils

def assert_that_evidence_df_scales_w_number_of_proteins(evidence_file, protein_groups_file, protein_groups_file_double):
    evidence_file_annotated = f"{evidence_file}.protgroup_annotated.tsv"
    directlfq.utils.add_mq_protein_group_ids_if_applicable_and_obtain_annotated_file(mq_file=evidence_file, mq_protein_group_file=protein_groups_file,  input_type_to_use="maxquant_evidence", columns_to_add=[])
    evidence_df_annotated = pd.read_csv(evidence_file_annotated, sep="\t")
    #display(evidence_df_annotated)
    length_annotated_single = len(evidence_df_annotated.index)
    directlfq.utils.add_mq_protein_group_ids_if_applicable_and_obtain_annotated_file(mq_file=evidence_file, mq_protein_group_file=protein_groups_file_double,  input_type_to_use="maxquant_evidence", columns_to_add=[])
    evidence_df_annotated = pd.read_csv(evidence_file_annotated, sep="\t")
    #display(evidence_df_annotated)
    length_annotated_double = len(evidence_df_annotated.index)
    assert length_annotated_double == length_annotated_single * 2

assert_that_evidence_df_scales_w_number_of_proteins(evidence_file, protein_groups_file, protein_groups_file_double)

In [14]:
import directlfq.utils
import pandas as pd
import numpy as np
def compare_number_of_datapoints_in_traces_w_protgroup_id_mapping(ion_file, protein_groups_file, evidence_file):
    ion_df = load_mq_dataframe(ion_file)
    protein2num_peptides_proteingroups_df = get_protein2num_peptides_proteingroups_df(protein_groups_file, evidence_file)
    protein2num_peptides_ion_df = get_protein2numpeptides_ion_df(ion_df)
    for protid in protein2num_peptides_ion_df.keys():
        num_ions_iondf = protein2num_peptides_ion_df[protid]
        num_ions_proteingroupsdf = protein2num_peptides_proteingroups_df[protid]
        print(f"protid: {protid}, num_ions_iondf: {num_ions_iondf}, num_ions_proteingroupsdf: {num_ions_proteingroupsdf}")
        assert num_ions_iondf == num_ions_proteingroupsdf

def load_mq_dataframe(example_mq_file):
    mq_df = pd.read_csv(example_mq_file, sep = "\t")
    mq_df = directlfq.utils.index_and_log_transform_input_df(mq_df)
    mq_df = mq_df.reindex(sorted(mq_df.columns, key= lambda x : get_fraction_number(x)), axis=1)
    return mq_df

def get_fraction_number(fraction_name):
    shortened_fraction = fraction_name.split("_")[1].replace("K", "")
    try:
        return int(shortened_fraction)
    except:
        return np.inf


def get_protein2num_peptides_proteingroups_df(protein_groups_file, evidence_file):
    protein_groups_df = pd.read_csv(protein_groups_file, sep = "\t", usecols=["Protein IDs", "Evidence IDs"])
    print(evidence_file)
    set_of_valid_evidence_ids = get_set_of_valid_evidence_ids(evidence_file)
    protein2num_peptides = {}
    for _, row in protein_groups_df.iterrows():
        evidence_ids = row["Evidence IDs"].split(";")
        evidence_ids = [x for x in evidence_ids if x in set_of_valid_evidence_ids]
        protid = row["Protein IDs"]
        protein2num_peptides[protid] = len(evidence_ids)
    return protein2num_peptides

def get_set_of_valid_evidence_ids(evidence_file):
    evidence_df = pd.read_csv(evidence_file, usecols=["id", "Intensity", "Sequence", "Modified sequence","Charge", "Raw file"], sep="\t")
    evidence_df = evidence_df[~evidence_df["Intensity"].isna()]
    return set(evidence_df["id"].astype('str'))


def get_protein2numpeptides_ion_df(ion_df):
    ion_df = ion_df.reset_index()
    numeric_columns = ion_df.select_dtypes(include=np.number).columns
    protein2numpeptides = {}
    for protid, df in ion_df.groupby("protein"):
        df_numeric = df[numeric_columns]
        #get number of non nan values in dataframe
        num_non_nan = df_numeric.count().sum()
        protein2numpeptides[protid] = num_non_nan
    return protein2numpeptides


list_of_protids_to_check = ['P35268', 'P33993;P33993-3;P33993-2', "Q9NQS1", "O95714;Q9BVR0", "Q9GZU8", "Q13510-2;Q13510;Q13510-3", "Q9NQS1", "P54886;P54886-2", "Q9GZU8", "Q9UP83-2;Q9UP83;Q9UP83-3"]

compare_number_of_datapoints_in_traces_w_protgroup_id_mapping(aq_reformatted_file, protein_groups_file_double, annotated_file)

../../test_data/system_tests/quicktests/mq_evidence/shortened_input.tsv.protgroup_annotated.tsv
protid: A1X283;G3V144;Q5TCZ1;H0Y507;Q5TCZ1-3, num_ions_iondf: 60, num_ions_proteingroupsdf: 60
protid: A6NDG6;H3BV17, num_ions_iondf: 169, num_ions_proteingroupsdf: 169
protid: A6NHR9;A6NHR9-2;J3KTL8;A6NHR9-3, num_ions_iondf: 140, num_ions_proteingroupsdf: 140
protid: A6NIH7, num_ions_iondf: 18, num_ions_proteingroupsdf: 18
protid: G3V150;O94766-2;O94766;E9PNA1;REV__A0A0C4DGF1;REV__Q9Y2Y4;REV__Q9BRK4, num_ions_iondf: 24, num_ions_proteingroupsdf: 24
protid: O00231;O00231-2;J3QRY4;J3QS13;J3KSW3, num_ions_iondf: 450, num_ions_proteingroupsdf: 450
protid: O15357;A0A0A0MTP6;O15357-2;F5GY16;H7BXR2;Q92835;H0YFZ4;Q92835-2;Q7Z7G1;F5H588;D6RJB9;A0A0A0MSJ4;H0Y5Q9;Q7Z7G1-3;Q92835-3, num_ions_iondf: 268, num_ions_proteingroupsdf: 268
protid: O43324;D6RBD7;C9J1V9;O43324-2;H0YAL7;D6RCQ0;H0YAH9, num_ions_iondf: 107, num_ions_proteingroupsdf: 107
protid: O75489;E9PS48;O75489-2;E9PJE7;E9PKL8;G3V194, num_ions_iondf: 135, num_ions_proteingroupsdf: 135
protid: O75822;O75822-2;O75822-3;H0YGJ7;H0YLP3, num_ions_iondf: 230, num_ions_proteingroupsdf: 230
protid: O95551;O95551-2;X6R5A3;O95551-3, num_ions_iondf: 36, num_ions_proteingroupsdf: 36
protid: P00452;P00452-2, num_ions_iondf: 245, num_ions_proteingroupsdf: 245
protid: P00959, num_ions_iondf: 301, num_ions_proteingroupsdf: 301
protid: P02786;G3V0E5;H7C3V5;F8WBE5;Q9UP52;Q9UP52-2;Q9UP52-3, num_ions_iondf: 548, num_ions_proteingroupsdf: 548
protid: P09417;P09417-2;B7Z415;D6RGG7;H0Y8F7;D6RHJ7, num_ions_iondf: 53, num_ions_proteingroupsdf: 53
protid: P0A6A6, num_ions_iondf: 33, num_ions_proteingroupsdf: 33
protid: P0A8I8, num_ions_iondf: 9, num_ions_proteingroupsdf: 9
protid: P0A8T7, num_ions_iondf: 967, num_ions_proteingroupsdf: 967
protid: P19934, num_ions_iondf: 32, num_ions_proteingroupsdf: 32
protid: P28482;P28482-2;H0YDH9, num_ions_iondf: 167, num_ions_proteingroupsdf: 167
protid: P36578;H3BM89;H3BTP7;H3BU31, num_ions_iondf: 349, num_ions_proteingroupsdf: 349
protid: P37108;H0YLA2;H0YLW0, num_ions_iondf: 119, num_ions_proteingroupsdf: 119
protid: P55036;Q5VWC4;P55036-2;A6PVX3;H0Y3Y9;H0Y561, num_ions_iondf: 135, num_ions_proteingroupsdf: 135
protid: P55263;P55263-3;P55263-2;P55263-4, num_ions_iondf: 159, num_ions_proteingroupsdf: 159
protid: Q01780;Q01780-2;K7EJ37, num_ions_iondf: 281, num_ions_proteingroupsdf: 281
protid: Q12972;Q12972-2;A0A0A0MT09;Q12972-3, num_ions_iondf: 141, num_ions_proteingroupsdf: 141
protid: Q13049;Q5JVY0, num_ions_iondf: 25, num_ions_proteingroupsdf: 25
protid: Q15005;E9PL01;A0A087WUC6;E9PI68;E9PRB9;H0YE04, num_ions_iondf: 55, num_ions_proteingroupsdf: 55
protid: Q6QNY1, num_ions_iondf: 26, num_ions_proteingroupsdf: 26
protid: Q7L5D6;Q7L5D6-2;C9JPA8;C9JHN8;C9JY46, num_ions_iondf: 57, num_ions_proteingroupsdf: 57
protid: Q8N1G4, num_ions_iondf: 280, num_ions_proteingroupsdf: 280
protid: Q8WVM8;Q8WVM8-2;Q8WVM8-3;J3KNG4;G3V4I1;G3V5F3;G3V2M8;G3V3K9;G3V363;H0YJS6;H0YJY1;H0YIZ7;G3V5E2, num_ions_iondf: 168, num_ions_proteingroupsdf: 168
protid: Q96IV0;Q96IV0-3;Q96IV0-2;H0Y2P2;A0A0C4DFP4;Q96IV0-5, num_ions_iondf: 8, num_ions_proteingroupsdf: 8
protid: Q96JP5;A0A0A6YYC7;Q96JP5-2;H3BTR0;Q9BU19;Q9BU19-2;H0YCH4;Q9BU19-3;Q9BU19-5, num_ions_iondf: 43, num_ions_proteingroupsdf: 43
protid: Q96P70;Q5SVH5, num_ions_iondf: 330, num_ions_proteingroupsdf: 330
protid: Q99615;Q99615-2;K7ESP1;K7EIH8;K7EPP7;K7ER44;K7EJV7;K7EJL5;K7EN19;K7ELJ8;K7EJE9;K7EK03;K7EJ24;K7ENB7;K7EQ73, num_ions_iondf: 352, num_ions_proteingroupsdf: 352
protid: Q99873-4;Q99873;H7C2I1;Q99873-3;Q99873-2;E9PKG1;E9PIX6;A0A087X1W2;E9PQ98;H0YDE4;E9PNR9;Q9NR22;E9PMW9;E9PI83;Q9NR22-2;E9PMZ2, num_ions_iondf: 225, num_ions_proteingroupsdf: 225
protid: Q99942, num_ions_iondf: 10, num_ions_proteingroupsdf: 10
protid: Q9H5N1;Q9H5N1-2;B4DHR0;H3BT64;H3BU67;H3BNR2;H3BNR8, num_ions_iondf: 50, num_ions_proteingroupsdf: 50
protid: Q9H9Y2;X6R7Q1, num_ions_iondf: 55, num_ions_proteingroupsdf: 55
protid: Q9HD20;Q9HD20-2;H7C3H2;Q9HD20-3, num_ions_iondf: 111, num_ions_proteingroupsdf: 111
protid: Q9NQP4;E9PQY2, num_ions_iondf: 27, num_ions_proteingroupsdf: 27
protid: Q9NR33, num_ions_iondf: 20, num_ions_proteingroupsdf: 20
protid: Q9P258, num_ions_iondf: 270, num_ions_proteingroupsdf: 270
protid: Q9UID3;E9PRV0;E9PKX7;Q9UID3-2;E9PJ36;E9PMB6;E9PQD5;E9PKE5;E9PQN6;H0YEE1, num_ions_iondf: 43, num_ions_proteingroupsdf: 43
protid: Q9UNF1;Q5H909;Q9UNF1-2;Q5H907;Q9Y5V3;Q12816;A0A087X070;G5E9N2;Q12816-5;Q12816-2;Q9Y5V3-2;Q12816-3;Q12816-4, num_ions_iondf: 212, num_ions_proteingroupsdf: 212
protid: Q9UPT8;M0QY97, num_ions_iondf: 87, num_ions_proteingroupsdf: 87
protid: Q9Y2U8, num_ions_iondf: 76, num_ions_proteingroupsdf: 76
protid: Q9Y2Z0;Q9Y2Z0-2, num_ions_iondf: 249, num_ions_proteingroupsdf: 249
protid: REV__P83731, num_ions_iondf: 10, num_ions_proteingroupsdf: 10

# Learning Tests

In [5]:
import seaborn as sns
petal_df = sns.load_dataset("iris")
petal_df = petal_df.drop_duplicates(subset=["sepal_length"]).iloc[:10]
display(petal_df)
surjective_mapping_df = pd.DataFrame({"species" : petal_df["species"], "sepal_length" : petal_df["sepal_length"]})
#add one more row to the surjective mapping
surjective_mapping_df = surjective_mapping_df.append({"species" : "newspecies", "sepal_length" : 5.1}, ignore_index=True)
display(surjective_mapping_df)

merged_df = petal_df.merge(surjective_mapping_df, left_on="sepal_length", right_on = "sepal_length", how="right", suffixes=("", "_right"))
display(merged_df)

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
8            4.4          2.9           1.4          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa

/var/folders/wb/j08kzzbd2hd8838tn3ll0jfm0000gn/T/ipykernel_9893/984504079.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  surjective_mapping_df = surjective_mapping_df.append({"species" : "newspecies", "sepal_length" : 5.1}, ignore_index=True)

       species  sepal_length
0       setosa           5.1
1       setosa           4.9
2       setosa           4.7
3       setosa           4.6
4       setosa           5.0
5       setosa           5.4
6       setosa           4.4
7       setosa           4.8
8       setosa           4.3
9       setosa           5.8
10  newspecies           5.1

    sepal_length  sepal_width  petal_length  petal_width species species_right
0            5.1          3.5           1.4          0.2  setosa        setosa
1            4.9          3.0           1.4          0.2  setosa        setosa
2            4.7          3.2           1.3          0.2  setosa        setosa
3            4.6          3.1           1.5          0.2  setosa        setosa
4            5.0          3.6           1.4          0.2  setosa        setosa
5            5.4          3.9           1.7          0.4  setosa        setosa
6            4.4          2.9           1.4          0.2  setosa        setosa
7            4.8          3.4           1.6          0.2  setosa        setosa
8            4.3          3.0           1.1          0.1  setosa        setosa
9            5.8          4.0           1.2          0.2  setosa        setosa
10           5.1          3.5           1.4          0.2  setosa    newspecies